name: bugsnag_crashlytics
description: Flutter plugin for Bugsnag Crashlytics. It reports uncaught errors to the
  Bugsnag console.
version: 1.0.0
homepage: https://github.com/Moujarkash/bugsnag-crashlytics

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: mod.flutter.plugins.bugsnag.crashlytics.bugsnag_crashlytics
        pluginClass: BugsnagCrashlyticsPlugin
      ios:
        pluginClass: BugsnagCrashlyticsPlugin
